### ISSUE TITLE
Plugin Integration Bug

### ISSUE THREAD

**Issue by sladyn98** [papercups-io/papercups#528]
I tried integrating the plugin to the papercups app however it is not getting authenticated. 
`Error: Error: cannot POST /api/v1/messages (401)
        at Response.toError (/home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/node/response.js:98:13)
        at ResponseBase._setStatusProperties (/home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/response-base.js:119:48)
        at new Response (/home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/node/response.js:44:8)
        at Request._emitResponse (/home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/node/index.js:930:18)
        at /home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/node/index.js:1127:42
        at IncomingMessage.<anonymous> (/home/sladyn/BotCart/webhooks-demo/node_modules/superagent/lib/node/parsers/json.js:22:7)
        at IncomingMessage.emit (events.js:208:15)
        at endReadableNT (_stream_readable.js:1161:12)
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      status: 401,
      text: '{"error":{"code":401,"message":"Not authenticated"}}',
      method: 'POST',
      path: '/api/v1/messages'
    },
`

**Comment by utkusaglm** [comment]
Is there any update?
