### ISSUE TITLE
Can't get slack integration to work

### ISSUE THREAD

**Issue by ThisIsQasim** [papercups-io/papercups#584]
**Describe the bug**
I am trying to setup Slack integration on a self hosted papercups setup. I have created a new slack app as mentioned in the wiki and added the required environment variables but the integrations tabs still redirects to the Papercups slack app instead of my own. I am also seeing the following in the logs

```
papercups_1  | 12:36:03.921 [error] GenServer #PID<0.5050.0> terminating
papercups_1  | ** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:418: value `"lobby:2e86fdcc-41fa-47a1-8557-2ace7e41131e"` cannot be dumped to type :binary_id in query:
papercups_1  | 
papercups_1  | from c0 in ChatApi.Conversations.Conversation,
papercups_1  |   where: c0.id == ^"lobby:2e86fdcc-41fa-47a1-8557-2ace7e41131e",
papercups_1  |   select: c0
papercups_1  | 
papercups_1  |     (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
papercups_1  |     (elixir 1.10.4) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
papercups_1  | Last message: {Phoenix.Channel, %{}, {#PID<0.4894.0>, #Reference<0.2882087684.1225523201.191388>}, %Phoenix.Socket{assigns: %{}, channel: ChatApiWeb.ConversationChannel, channel_pid: nil, endpoint: ChatApiWeb.Endpoint, handler: ChatApiWeb.UserSocket, id: nil, join_ref: "121", joined: false, private: %{}, pubsub_server: ChatApi.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "conversation:lobby:2e86fdcc-41fa-47a1-8557-2ace7e41131e", transport: :websocket, transport_pid: #PID<0.4894.0>}}
papercups_1  | 12:36:03.922 [error] an exception was raised:
papercups_1  |     ** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:418: value `"lobby:2e86fdcc-41fa-47a1-8557-2ace7e41131e"` cannot be dumped to type :binary_id in query:
papercups_1  | 
papercups_1  | from c0 in ChatApi.Conversations.Conversation,
papercups_1  |   where: c0.id == ^"lobby:2e86fdcc-41fa-47a1-8557-2ace7e41131e",
papercups_1  |   select: c0
papercups_1  | 
papercups_1  |         (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
papercups_1  |         (elixir 1.10.4) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

**Comment by reichert621** [comment]
hey @ThisIsQasim! did you modify any of the code before you deployed?

it might be easiest to hop on a call sometime this week and help you debug... feel free to book a time on https://calendly.com/alex-reichert/ and I'd be happy to help

**Comment by ThisIsQasim** [comment]
No. I am using the default docker image. Meanwhile, I have scheduled a call for today.

**Comment by reichert621** [comment]
sounds good @ThisIsQasim — I wonder if our docker image is out of date? cc @cheeseblubber

**Comment by ThisIsQasim** [comment]
It's the latest image.

**Comment by cheeseblubber** [comment]
@ThisIsQasim pushed a fix for the docker release this week going to close for now feel free to reopen if this didn't fix the issue
